django/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.page, name="page"),
    path("search", views.search, name="search"),
    path("newpage", views.newpage, name="newpage"),
    path("editpage/<str:title>", views.editpage, name="editpage"),
    path("random", views.random, name="random")
]

django/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

django/wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from markdown2 import Markdown
from . import util
from random import choices

# Creates a form
class NewForm(forms.Form):
    forms = forms.CharField(label='', 
                    widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

# enable markdown module
markdowner = Markdown()

# display index page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(), 
        "form": NewForm
    })

# Display entries
def page(request, title):
    if not util.get_entry(title):
        return render(request, "encyclopedia/error.html", {
                "message": "Content not available"
            })
    else:
        md = util.get_entry(title)
        data = markdowner.convert(md)
        return render(request, "encyclopedia/entry.html", {
            "data": data, "form": NewForm, "title": title
        })

# perform search funtion
def search(request):
    if request.method == "POST":
        form = NewForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["forms"]

    
    if util.get_entry(title):
        return HttpResponseRedirect(f'wiki/{title}')


    possible_entry = []
    for entry in util.list_entries():
        if title.lower() in entry.lower():
            possible_entry.append(entry)
    return render(request, "encyclopedia/search.html", {
        "entries": possible_entry, 
        "form": NewForm
    })

# create new page
def newpage(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')

        if not (title and content):
           return render(request, "encyclopedia/error.html", {
                "message": "Enter the details"
            }) 
        if title.isspace() or content.isspace():
            return render(request, "encyclopedia/error.html", {
                "message": "Enter the details"
            }) 

        if util.get_entry(title) != None:
            return render(request, "encyclopedia/error.html", {
                "message": "Page already exists"
            })
        else:
            util.save_entry(title, content)
            return HttpResponseRedirect(f'/wiki/{title}')

    else:
        return render(request, "encyclopedia/newpage.html")

# enable page edit feature
def editpage(request, title):

    if request.method == 'POST':

        title = request.POST.get('title')
        content = request.POST.get('content')

        if not (title and content):
           return render(request, "encyclopedia/error.html", {
                "message": "Enter the details"
            }) 
        if title.isspace() or content.isspace():
            return render(request, "encyclopedia/error.html", {
                "message": "Enter the details"
            })

        util.save_entry(title, content)
        return HttpResponseRedirect(f'/wiki/{title}')

    else:
        content = util.get_entry(title)
        return render(request, "encyclopedia/editpage.html", {
            "title": title,
            "content": content
        })

# select random page using random module
def random(request):
    list_of_titles = util.list_entries()
    title = choices(list_of_titles)[0]
    return HttpResponseRedirect(f'/wiki/{title}')

django/wiki/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %} {% block title %} Edit page {% endblock %}
{% block body %}

<h1 class="mb-3">Edit Page</h1>

<form action="{% url 'encyclopedia:editpage' title  %}" method="post">
    {% csrf_token %}
    <div class="form-group mb-3">
      <input type="text" class="form-control w-75" id="title" name="title" placeholder="Enter title here" value="{{ title }}">
    </div>
    <div class="form-group mb-3">
      <textarea class="form-control w-75" id="content" name="content" placeholder="Enter content here in Markdown format" rows="20">{{ content }}</textarea>
    </div>
    <div class="form-group mb-3">
        <button type="submit" class="btn btn-success px-5">Save Changes</button>
      </div>
  </form>

{% endblock %}

django/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %} 
{% block title %} {{ title }} {% endblock %}

{% block body %}
{{ data |safe }}
<div class="mt-5">
    <button class="btn btn-secondary"><a href="{% url 'encyclopedia:editpage' title %}"style="text-decoration: none; color: white;">Edit Page</a></button>  
</div>
{% endblock %}

django/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %} 
{% block title %} Error {% endblock %}

{% block body %}
<h1 class="text-center mb-5">Error!!</h1>
<h5 class="text-center" >{{ message }}</h5>
{% endblock %}

django/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:page' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

django/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <!-- <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                </form>
                
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

django/wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %} {% block title %} Create new page {% endblock %}
{% block body %}

<h1 class="mb-3">Create New Page</h1>

<form action="{% url 'encyclopedia:newpage' %}" method="post">
    {% csrf_token %}
    <div class="form-group mb-3">
      <input type="text" class="form-control w-75" id="title" name="title" placeholder="Enter title here">
    </div>
    <div class="form-group mb-3">
      <textarea class="form-control w-75" id="content" name="content" placeholder="Enter content here in Markdown format" rows="20"></textarea>
    </div>
    <div class="form-group mb-3">
        <button type="submit" class="btn btn-success px-5">Submit</button>
      </div>
  </form>

{% endblock %}

django/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:page' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}